### ISSUE TITLE
Can't run basic_example_v1

### ISSUE THREAD

**Issue by culhatsker** [yandex-cloud/ydb-python-sdk#3]
```
$ python3 __main__.py -e grpcs://ydb.serverless.yandexcloud.net:2135 -d /ru-central1/b1gm2tv7d86buf61nlae/etn03r5dvf1fe0omp0dm
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
    import basic_example
  File "/home/username/misc/cloud_funcs/ydb-python-sdk/examples/basic_example_v1/basic_example.py", line 4, in <module>
    from kikimr.public.sdk.python import client as ydb
  File "/home/username/.local/lib/python3.8/site-packages/kikimr/public/sdk/python/client/__init__.py", line 2, in <module>
    from .experimental import *  # noqa
  File "/home/username/.local/lib/python3.8/site-packages/kikimr/public/sdk/python/client/experimental.py", line 3, in <module>
    from . import _utilities, issues, convert
  File "/home/username/.local/lib/python3.8/site-packages/kikimr/public/sdk/python/client/convert.py", line 6, in <module>
    from . import issues, types, _apis
  File "/home/username/.local/lib/python3.8/site-packages/kikimr/public/sdk/python/client/types.py", line 8, in <module>
    class PrimitiveType(enum.Enum):
  File "/home/username/.local/lib/python3.8/site-packages/kikimr/public/sdk/python/client/types.py", line 13, in PrimitiveType
    Int32 = _apis.primitive_types.INT32, 'int32_value'
AttributeError: 'EnumTypeWrapper' object has no attribute 'INT32'
```

OS: Ubuntu 20.04.1 LTS
Python version: Python 3.8.5

```bash
$ python3 -m pip freeze | grep -E "(protobuf|grpcio|enum-compat)"
enum-compat==0.0.3
grpcio==1.32.0
protobuf==3.6.1
```

**Comment by MihanixA** [comment]
Hi, @culhatsker
Please try upgrading protobuf to `protobuf==3.13.0`

**Comment by culhatsker** [comment]
Upgrading protobuf did the thing, thank you!
